[build]
  command = "pip install -r requirements.txt"
  functions = "netlify/functions"
  publish = "public"

[build.environment]
  PYTHON_VERSION = "3.9"
  ODDS_API_KEY = "fe3e1db58259d6d7d3599e2ae3d22ecc"

[[redirects]]
  from = "/analyze"
  to = "/.netlify/functions/analyze"
  status = 200